title: LeetCode Solutions
description: My LeetCode problem solving journey
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

github:
  is_project_page: false